# Generated by Django 3.1.7 on 2021-08-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='quantitiy',
            new_name='quantity',
        ),
    ]
