# Generated by Django 3.1.7 on 2021-08-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20210803_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
